apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: kvm-csi-driver
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: kvm-csi-driver
  name: kvm-csi-driver
  namespace: kvm-csi-driver
spec:
  selector:
    matchLabels:
      app: kvm-csi-driver
  template:
    metadata:
      labels:
        app: kvm-csi-driver
    spec:
      containers:
        - image: ghcr.io/onlineque/kvmcsidriver:main
          imagePullPolicy: Always
          name: kvm-csi-driver
          resources: {}
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /csi
              name: plugin-dir
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
        - args:
            - --v=0
            - --csi-address=/csi/csi.sock
            - --kubelet-registration-path=/var/lib/kubelet/plugins/example.csi.clew.cz/csi.sock
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.7.0
          imagePullPolicy: IfNotPresent
          name: driver-registrar
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /csi
              name: plugin-dir
            - mountPath: /registration
              name: registration-dir
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-k2fkp
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/example.csi.clew.cz/
            type: DirectoryOrCreate
          name: plugin-dir
        - hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
          name: registration-dir
        - name: kube-api-access-k2fkp
          projected:
            defaultMode: 420
            sources:
              - serviceAccountToken:
                  expirationSeconds: 3607
                  path: token
              - configMap:
                  items:
                    - key: ca.crt
                      path: ca.crt
                  name: kube-root-ca.crt
              - downwardAPI:
                  items:
                    - fieldRef:
                        apiVersion: v1
                        fieldPath: metadata.namespace
                      path: namespace
---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: example.csi.clew.cz
spec:
  attachRequired: false
  fsGroupPolicy: File
  podInfoOnMount: false
  requiresRepublish: false
  seLinuxMount: false
  storageCapacity: false
  volumeLifecycleModes:
    - Persistent
---
allowVolumeExpansion: false
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: example-csi
provisioner: example.csi.clew.cz
reclaimPolicy: Delete
volumeBindingMode: Immediate
