apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: testpod
  name: testpod
spec:
  containers:
    - image: nginx
      name: testpod
      resources: {}
      volumeMounts:
        - name: test-pvc
          mountPath: /test
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - persistentVolumeClaim:
        claimName: test-pvc
      name: test-pvc
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Mi
  storageClassName: example-csi
