apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kvm-csi-driver.fullname" . }}-controller-role-binding
  labels:
  {{- include "kvm-csi-driver.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "kvm-csi-driver.fullname" . }}-controller-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "kvm-csi-driver.fullname" . }}-controller-sa'
  namespace: '{{ .Release.Namespace }}'