apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kvm-csi-driver.fullname" . }}-controller-role
  labels:
  {{- include "kvm-csi-driver.labels" . | nindent 4 }}
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - watch
  - list
  - delete
  - update
  - create