apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kvm-csi-driver.fullname" . }}-controller
  labels:
    app: kvm-csi-driver-controller
  {{- include "kvm-csi-driver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      app: kvm-csi-driver-controller
    {{- include "kvm-csi-driver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: kvm-csi-driver-controller
      {{- include "kvm-csi-driver.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args:
        - controllerserver
        env:
        - name: STORAGEAGENT_TARGET
          value: {{ quote .Values.storageAgent.target }}
        image: {{ .Values.controller.kvmcsidriver.image.repository }}:{{ .Values.controller.kvmcsidriver.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.controller.kvmcsidriver.imagePullPolicy }}
        name: kvmcsidriver
        resources: {}
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-fz2wq
          readOnly: true
      - args:
        - --csi-address=$(ADDRESS)
        - --v=0
        - --timeout=2m30s
        - --retry-interval-start=500ms
        - --leader-election=true
        - --leader-election-namespace=kvm-csi-driver
        - --leader-election-lease-duration=137s
        - --leader-election-renew-deadline=107s
        - --leader-election-retry-period=26s
        - --extra-create-metadata=true
        env:
        - name: ADDRESS
          value: {{ quote .Values.controller.csiProvisioner.env.address }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.controller.csiProvisioner.image.repository }}:{{ .Values.controller.csiProvisioner.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.controller.csiProvisioner.imagePullPolicy }}
        name: csi-provisioner
        resources: {{- toYaml .Values.controller.csiProvisioner.resources | nindent 10
          }}
        securityContext: {{- toYaml .Values.controller.csiProvisioner.containerSecurityContext
          | nindent 10 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-fz2wq
          readOnly: true
      serviceAccountName: {{ include "kvm-csi-driver.fullname" . }}-controller-sa
      volumes:
      - emptyDir:
          medium: Memory
        name: socket-dir
      - name: kube-api-access-fz2wq
        projected:
          defaultMode: 420
          sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
              - key: ca.crt
                path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
              - fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
                path: namespace