apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: example.csi.clew.cz
  labels:
  {{- include "kvm-csi-driver.labels" . | nindent 4 }}
spec:
  attachRequired: false
  fsGroupPolicy: File
  podInfoOnMount: false
  requiresRepublish: false
  seLinuxMount: false
  storageCapacity: false
  volumeLifecycleModes:
  - Persistent