apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: example-csi
  labels:
  {{- include "kvm-csi-driver.labels" . | nindent 4 }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
allowVolumeExpansion: false
provisioner: example.csi.clew.cz
reclaimPolicy: Delete
volumeBindingMode: Immediate