apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kvm-csi-driver-controller-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kvm-csi-driver-controller-role
subjects:
  - kind: ServiceAccount
    name: kvm-csi-driver-controller-sa
