apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kvm-csi-driver.fullname" . }}-controller-sa
  labels:
  {{- include "kvm-csi-driver.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerSa.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kvm-csi-driver.fullname" . }}-sa
  labels:
  {{- include "kvm-csi-driver.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.sa.serviceAccount.annotations | nindent 4 }}