name: ci-helm-ghcr
permissions:
  packages: write
  contents: read
on:
  push:
    # Publish semver tags as releases.
    tags: [ '**' ]
env:
  CHART_NAME: kvm-csi-driver
  IMAGE_TAG: ${{ github.ref_name }}
jobs:
  release-helmchart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: helm lint
        run: |
          helm lint helm/kvm-csi-driver
      - name: helm login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u $ --password-stdin
      - name: helm package
        run: |
          helm package helm/kvm-csi-driver --version $IMAGE_TAG
      - name: show dir
        run: |
          ls -la
          ls -la helm/
      - name: helm push
        if: ${{ github.event_name == 'push' }}
        run: |
          helm push $CHART_NAME-$IMAGE_TAG.tgz oci://ghcr.io/${{ github.repository_owner }}
